# MCPWorkload Custom Resource Definition

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcpworkloads.mcp.security.gov
spec:
  group: mcp.security.gov
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              properties:
                workloadType:
                  type: string
                workloadName:
                  type: string
                namespace:
                  type: string
                labels:
                  type: object
                  additionalProperties:
                    type: string
  scope: Namespaced
  names:
    plural: mcpworkloads
    singular: mcpworkload
    kind: MCPWorkload
    shortNames:
      - mw
